//
// Generated file, do not edit! Created by nedtool 5.6 from src/ElectRoot.msg.
//

#ifndef __ELECTROOT_M_H
#define __ELECTROOT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/ElectRoot.msg:4</tt> by nedtool.
 * <pre>
 * message ElectRootMsg
 * {
 *     int id;
 * }
 * </pre>
 */
class ElectRootMsg : public ::omnetpp::cMessage
{
  protected:
    int id;

  private:
    void copy(const ElectRootMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ElectRootMsg&);

  public:
    ElectRootMsg(const char *name=nullptr, short kind=0);
    ElectRootMsg(const ElectRootMsg& other);
    virtual ~ElectRootMsg();
    ElectRootMsg& operator=(const ElectRootMsg& other);
    virtual ElectRootMsg *dup() const override {return new ElectRootMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ElectRootMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ElectRootMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ELECTROOT_M_H

